networks:
  payment-processor:
    external: true
  rinha-network:
    driver: bridge

services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "9999:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    networks:
      - rinha-network
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "60MB"

  app1:
    build: .
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSTANCE_ID=app1
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  app2:
    build: .
    networks:
      - rinha-network
      - payment-processor
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INSTANCE_ID=app2
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "100MB"

  redis:
    image: redis:7.2-alpine
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - rinha-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 2s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"
